name: Deploy Prod

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy prod
    uses: bancodebogota/bbog-can-pipeline/.github/workflows/deploy_react_frontend.yml@v1
    with:
      project-name: "" # No llenar este campo
      app-name: "kata-frontend"
      environment: "pr"
      aws-region: "us-east-1"
      build-folder: "dist"
      bucket: "kata-frontend-production"
      distribution-id: "" # Configurar con el CloudFront Distribution ID de Production
      build-command: "npm run build"
      node-version: "20.x"
      version: $(node -p "require('./package.json').version")
      sherpa-report: 'false'
      new-structure-folder: true
    secrets:
      DIG_READER_GITHUB_ACCESS_TOKEN: ${{ secrets.DIG_READER_GITHUB_ACCESS_TOKEN }}
      ARTIFACTORY_READER_USER: ${{ secrets.ARTIFACTORY_READER_USER }}
      ARTIFACTORY_READER_API_KEY: ${{ secrets.ARTIFACTORY_READER_API_KEY }}
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ROLE_DEPLOY_FRONTEND: ${{ secrets.AWS_ROLE_DEPLOY_FRONTEND }}
